<?php

namespace AppBundle\Repository;

use AppBundle\Entity\League;

/**
 * LeagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueRepository extends \Doctrine\ORM\EntityRepository
{
    public function createLeague($data){

        $league = new League();
        $league->setName($data['name']);

        $em = $this->getEntityManager();
        $em->persist($league);
        $em->flush();

        return $league;
    }

    public function deleteLeague($data){
        $league = $this->findOneById($data['league_id']);

        $em = $this->getEntityManager();
        $em->remove($league);
        $em->flush();

        return true;
    }
}
