<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Team;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function createTeam($data){

        $team = new Team();
        $team->setName($data['name']);
        $team->setStrip($data['strip']);

        $em = $this->getEntityManager();
        $em->persist($team);
        $em->flush();

        return $team;
    }

    public function updateTeam($team, $data){
        $team->setName($data['name']);
        $team->setStrip($data['strip']);

        $em = $this->getEntityManager();
        $em->persist($team);
        $em->flush();

        return $team;
    }

    public function deleteTeam($data){
        $team = $this->findOneById($data['id']);

        $em = $this->getEntityManager();
        $em->remove($team);
        $em->flush();

        return true;
    }
}
